spring:
  application:
    name: file-service
  datasource:
    url: jdbc:h2:mem:book
    driver-class-name: org.h2.Driver
    username: file
    password: file
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org: DEBUG

integrations:
  dontpad:
    url: "https://api.dontpad.com"
